print("NUMBER OPERATIONS")
a=int(input("first number "))
b=int(input("second number "))
sum=(a)+(b)
diff=int(a)-int(b)
mull=int(a)*int(b)
div=int(a)/int(b)
print("The sum is", sum)
print("The difference is", diff)
print("The product is", mull)
print("The divission is", div)
